travis:
  secure:
    BINSTAR_TOKEN: TW080TVhT8uXqIYnKH/6FA9hg22UyYoq5+gT9INfXOjPeLjjUjtRWKFkiDY9CD7Wj5E/kdPb2aNViqp1b3t6ZYbe9xdUAbOOfgkybj7yATZAwpwb2SiyA+8kFMWJfJQMcdhOttBAmK7wYokV++Yy9JPaDGbDgQ0vG70OJxrR3tmZ2CZqsEFtnV8cHd231DfQwaraKVn4O5aQEkMn5cDwFzDQqC3f06PUt2A4kFtDBY1yt3K4L5WClLq6D9U78AmwLdrUNCUbI/b79LBdr6c/7f0OZBhQ+t9AT2GFZK8TDcc/0lfPlg5+4Xv9/qOGF4j0TMHnTvy08Q9bUjaDLYGKj7Bf7mrT9w7Jr40yQYv6KpXW9/czCk+tcSTy2YqDVSamg8dDA1dVsugHGxuPGdr3rgpEFR+9OPgy6DpncmT/9Goh+0+OHvaANeTYPMTMpr+y6rfmTugRxqgPrgxTZ0USv9ZIBKHRjxFBwH8QnxqDbtLfUrqz5oSbF+uUo1GV573WeVJdoFYpfqF6Am34VSXLSEumKmZLXpaSqodRsb5vcZifbLw6cic65sjJUnD11IsUdiOy2n+/N4mdperVBDe//EmjbYcGk0yrRDYLWZ99B6241MAkPIxYI8twyOQe5s2qr8eQyD8f24wkz2qb6+FS12L16zM6rVI+wDfJyc8y5B4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
