travis:
  secure:
    BINSTAR_TOKEN: fFMKf3lYQamjH+WbUQere2w5C0fJHnXwh7SmHzrRYeWphZPMl9OhpEMq8fbhJ+k7ECJ7K/S8axuMBGw8VMnJ4xU+oTxnCvvX8W4LczdnX2dvbAYKE26T/LFlHF11xX/nRMrqcs3uEDcdCtv87CQnpipK1b92cph8doT0YKc7wNn4Cwwl5xhZgLbNiyC9/Int/nS/M+BOLucRPzB45MMgoNQ0a2H0QRLsFVubucs/tW27RZu7ySwvuJBHqE7z28chFYptwQ+m6HE/N9NX6JgkRo8bOiRAXeLYokbZ9HDwQW4Zw+W+vFZhDBeckwhF3W3JyfAajX4fz+92XQf1ogxmXVHXZ3+ieyB+lre6Zd/K/WVpb7mQdM0BsVEdnAnzF7vk9p6Met/Ik/FaAKlWbVHhW1xMJ6A9iCAhKs9l8XW+SSl1QEe0vn6XzHweHATRgE7e91FrAdasqkKmCuM3WIkvtJOIUK+Zr4uOtxd+/5qzfsnxAGKE92i44RN7HnN+pwyPWZlEINahwF6E/jJGgR5pBhf3/0L76AwR/PqXTc27lyEhZBrlzd1bDbF8IKWSlqYYg1Mo3VHFxQ1NYkXyASg6dFK7X5EHL3+9B0CC7MQ0hsmzRIWYqTYbyrXNfApT7e7yRREK1cZ/TeIcjaHLEbqxFHeiwcFXdsQXwTITKBOgZwk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
