travis:
  secure:
    BINSTAR_TOKEN: YWW6wIj3aPeRo9BWsZ4gE/pFiQyRMRTOVdSCuoc9DaBVxRTsrf403Ef14H6Q7Aq8iQDYyJomsEdhI0ThhWnrIdrfVnq6EKYA5WHvEWS05letC7+ICmmFlAL/LctR5ByqVtdu4CMfg6awTAbvMWngYdwk2f1BsBmzvfD3frGD4uemju+uhmv0oODt7XDEVCmKA2oDXC/FxpN8/LzjPR83evePIThPGrMxl6v81GJy9lpZk8TNB6DLqoOInpMQ5h01n2oXkkw2MD4GvcnTvMoZiRNCB+etgW7PVGY0XvWuVmamC6WuU52v58/Mqc2wPgFaq9xNvnQjgrC4GakqkvVgAbOhEQKlxF1lzTQOXSYWanzknr1dR9yFLctOxbjUPwqI0ngWOoCod0+YY8iP8GFpdy/V7xbTLvi3xO4npg8H3YZ6vcwZVlNnuxZdqIopTbfFtyKr3OdmjAx+p+m+/bFNgCDiwpOlp0KuS1LX6GIS70UKot8GI3d9K9JTCwsyUZ4UQq2n6LFjrPwF7umWvz6wCsVBR2ookDVGFoL6xXRoC5Xh04fyYrAYnR8FNSFZlJ9bim9e993ZwfguXtikhIiqxBOE5IpIDunZWf8hR0bmt3QF8usNa8yOpMe5Nn9pnVx/v9l3vekdEromLrjmpmXnqxkoWkLalHdjRGGY2GgmKnI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
